#!/bin/csh
#
# set_camera_mode [driftscan/stare]
#
# write the date and either "driftscan" or "stare" in the camera_mode file.
#
set CAMERA_MODE_FILE = "/home/observer/.camera_mode"
#
if ( $#argv != 1 ) then
   echo "syntax: set_camer_mode [driftscan/tare]"
   exit
endif
#
if ( $argv[1] == "driftscan" || $argv[1] == "DRIFTSCAN" || $argv[1] == "Driftscan" ) then
   echo `date` "driftscan" >! $CAMERA_MODE_FILE
else if ( $argv[1] == "stare" || $argv[1] == "STARE" || $argv[1] == "Stare" ) then
   echo `date` "stare" >! $CAMERA_MODE_FILE
else
   echo "set_camera_mode: $argv[1] not a valid argument"
endif
exit
#

