/* convert_fields.c

   Read fields generated by Greg Aldering and write out in format
   expected by scheduler program. Put field priority and grid index
   in comment field

*/

#include<stdio.h>

#define SNE_SURVEY_CODE 2


main()
{
    char string[1024],s1[256],s2[256],s3[256],s4[256],s5[256],s6[256];
    char s7[256],s8[256],s9[256];

    printf("0.0      0.0      N 60.0 3600.0  12  0\n");
    printf("0.00000  0.0      F 10.0 60.0 7 0 0.05 26.65\n");
    printf("0.00000  0.0      E 10.0 10.0 10  0 \n"); 
    printf("0.00000  0.0      M 10.0 10.0 10  0 \n");
    printf("0.00000  0.0      P 10.0 10.0 1   0 \n");
  
    while(fgets(string,1024,stdin)!=NULL){
       sscanf(string,"%s %s %s %s %s %s %s %s %s",
          s1,s2,s3,s4,s5,s6,s7,s8,s9);

       printf("%s %s %s %s %s %s %d %s %s %s\n",
         s1,s2,s3,s4,s5,s6,SNE_SURVEY_CODE, s7,s8,s9);
    }

    exit(0);
}
