/* tabulate_sums.c

   read sums.all generated by read_sums.csh
   print tabulated values of number of observed fields:

   Region  Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
    1
    2
    3
    4

*/

#include <stdio.h>

typedef struct {
   int month;
   int count;
   int region;
   int date;
   int iteration;
} Entry;

#define MAX_ENTRIES 1000

main()
{
    Entry entry[MAX_ENTRIES],*e;
    char string[1024];
    int i,n,region,month,iteration,region_prev,total[12];
    int grand_total;
   
    n=0;
    iteration=1;
    region_prev=0;
    while(fgets(string,1024,stdin)!=NULL){
       e=entry+n;
       sscanf(string,"%d %d %d %d",
         &(e->month),&(e->count),&(e->region),&(e->date));
       if(e->region==region_prev){
           iteration++;
       }
       else{
           iteration=1;
           region_prev=e->region;
       }
       e->iteration=iteration;
       
       n++;
    }

    for(month=0;month<12;month++)total[month]=0;

    for(region=1;region<=4;region++){
       for(iteration=1;iteration<=5;iteration++){
         printf("%d   ", region);
         for(month=1;month<=12;month++){
            for(i=0;i<n;i++){
               if(entry[i].region==region&&entry[i].month==month&&
                     entry[i].iteration==iteration){
                  printf("%4d   ",entry[i].count);
                  total[month-1]=total[month-1]+entry[i].count;

                  if(i>0&&entry[i].date==entry[i-1].date+1){
                      if(entry[i].count>entry[i-1].count){
                         total[month-1]=total[month-1]-entry[i-1].count;
                      }
                      else{
                         total[month-1]=total[month-1]-entry[i].count;
                      }
                  }
                  i=n;
               }
            }
         }
         printf("\n");
       }
         printf("\n");
    }

    grand_total=0;

    printf("tot:");

    for(month=0;month<12;month++){

       printf("%4d   ",total[month]);
       grand_total=grand_total+total[month];

    }
    printf("\n");
    printf("grand total: %4d\n",grand_total);


    exit(0);
}
