/* tabulate_counts.c

   read file generated by get_counts.csh
   print tabulated values of number of fields covered
   for tnos, and then for supernova:

   Region  Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
    1
    2
    3
    4

*/

#include <stdio.h>

typedef struct {
   int month;
   int tno_count;
   int sne_count;
   int region;
} Entry;

#define MAX_ENTRIES 1000

main()
{
    Entry entry[MAX_ENTRIES],*e;
    char string[1024];
    int i,n,region,month,iteration,region_prev,total[12];
   
    n=0;
    while(fgets(string,1024,stdin)!=NULL){
       e=entry+n;
       sscanf(string,"%d %d %d %d",
         &(e->month),&(e->region),&(e->tno_count),&(e->sne_count));
        
       n++;
    }


    /* first tabulate tno counts */

    printf("\nTNO counts:\n\n");

    for(month=0;month<12;month++)total[month]=0;

    for(region=1;region<=4;region++){
         printf("%d   ", region);
         for(month=1;month<=12;month++){
            for(i=0;i<n;i++){
               if(entry[i].region==region&&entry[i].month==month){
                  printf("%4d   ",entry[i].tno_count);
                  total[month-1]=total[month-1]+entry[i].tno_count;
                  i=n;
               }
            }
         }
         printf("\n");
     }

    printf("tot:");
    for(month=0;month<12;month++){
       printf("%4d   ",total[month]);
    }
    printf("\n\n");


    /* now tabulate sne counts */

    printf("Sne counts:\n\n");

    for(month=0;month<12;month++)total[month]=0;

    for(region=1;region<=4;region++){
         printf("%d   ", region);
         for(month=1;month<=12;month++){
             for(i=0;i<n;i++){
               if(entry[i].region==region&&entry[i].month==month){
                  printf("%4d   ",entry[i].sne_count);
                  total[month-1]=total[month-1]+entry[i].sne_count;
                  i=n;
               }
            }
         }
         printf("\n");
     }

    printf("tot:");
    for(month=0;month<12;month++){
       printf("%4d   ",total[month]);
    }
    printf("\n\n");


    exit(0);
}
